#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fontsproto
Version  : 2.1.3
Release  : 3
URL      : http://xorg.freedesktop.org/releases/individual/proto/fontsproto-2.1.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/fontsproto-2.1.3.tar.gz
Summary  : Fonts extension headers
Group    : Development/Tools
License  : MIT-Opengroup
Requires: fontsproto-doc
BuildRequires : libxslt-bin
BuildRequires : xmlto

%description
X Fonts Extension
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the fontsproto package.
Group: Development

%description dev
dev components for the fontsproto package.


%package doc
Summary: doc components for the fontsproto package.
Group: Documentation

%description doc
doc components for the fontsproto package.


%prep
%setup -q -n fontsproto-2.1.3

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/fonts/FS.h
/usr/include/X11/fonts/FSproto.h
/usr/include/X11/fonts/font.h
/usr/include/X11/fonts/fontproto.h
/usr/include/X11/fonts/fontstruct.h
/usr/include/X11/fonts/fsmasks.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/fontsproto/*
